### PR TITLE
update to fly@0.7.0 new API

### PR DESCRIPTION
**Pull request by ghost**
This updates the plugin against the new API in 0.7.0.

Let me know if you have any questions / comments.

Regards

### CODE REVIEW

**Comment by msaktype** [comment]
@bucaran `eslint`, `tap-spec` and `tape` are not in devdependencies but dependencies. Is it right?

**Comment by ghost** [comment]
Wait, my bad.

**Comment by ghost** [comment]
:sweat_smile: I will ping you when I have this fixed. Sorry.

**Comment by msaktype** [comment]
Thanks :+1:

**Pull request merged**
